name: lambda-deployment-with-github-action-test

on:
  push:
    branches: main # You can use any of your root or master branch name

jobs:
  lambda-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install nestjs
        run: npm i -g @nestjs/cli

      - name: Install serverless globally
        run: npm install -g serverless

      - name: Install npm dependencies
        run: npm i

      - name: serverless plugin
        run: serverless plugin install -n serverless-offline

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 474437561333.dkr.ecr.us-east-2.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t nest-challenge .
          docker tag nest-challenge:latest 474437561333.dkr.ecr.us-east-2.amazonaws.com/nest-challenge:latest
          docker push 474437561333.dkr.ecr.us-east-2.amazonaws.com/nest-challenge:latest

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PORT: ${{ vars.PORT }}
          JWT_SECRET: ${{vars.JWT_SECRET}}
          DB_HOST: ${{vars.DB_HOST}}
          DB_PORT: ${{vars.DB_PORT}}
          DB_USER: ${{vars.DB_USER}}
          DB_PASS: ${{vars.DB_PASS}}
          DB_DATABASE: ${{vars.DB_DATABASE}}
